### ISSUE TITLE
replace public async Task<ActionResult<UserModel>> with Task<Results<Ok<UserModel>, BadRequest>>

### ISSUE THREAD

**Issue by ignatandrei** [adrian-badulescu/SiteFabrik#1]
please read Typed Results from https://www.telerik.com/blogs/whats-new-dotnet-7-minimal-apis
and replace with strongly typed

It is good for
1. Test
2. Clarity of returns

**Comment by adrian-badulescu** [comment]
In order to not brake the front end logic, I need to return Task<Results<Ok<**AuthResponse**>, "THE_OTHER_STATUS">>

Also I haven't managed to use BadRequest with TypedResults, instead I return **TypedResults.Forbid()**;, maybe you could provide me the full example for the Register endpoint.


``
        [HttpPost("Register")]
        public async Task<Results<Ok<AuthResponse>, ForbidHttpResult>> Register(LoginModel request)
        {
            try
            {
                
                if(ModelState.IsValid)
                {
                    
                    _userService.CreatePasswordHash(request.Password, out byte[] passwordHash, out byte[] passwordSalt);
                    _user.Email = request.Email;
                    _user.PasswordHash = passwordHash;
                    _user.PasswordSalt = passwordSalt;
                    _user.RefreshToken = string.Empty;
                    _user.TokenCreated = DateTime.UtcNow;
                    _user.TokenExpires = DateTime.UtcNow;
                   
                    await _userData.CreateUser(_user);
                    var token = _userService.CreateToken(_user);

                    return TypedResults.Ok(new AuthResponse(true, string.Empty, token));
                    
                }

                return TypedResults.Forbid();
                
            }
            catch (Exception ex)
            {
                _logger.LogError("error into Auth Controller on Register() " + ex.Message);
                throw;
            }

        }
``
