### ISSUE TITLE
Business Logic: Move code from CreateTemplate  into a BL

### ISSUE THREAD

**Issue by ignatandrei** [adrian-badulescu/SiteFabrik#3]
The code from public async Task CreateTemplate 

does more than 1 thing
``` charp
try
            {                
                await _templateManagement.CreateDirectoryAndTemplate(template);
                await _templateData.InsertTemplate(template);
                return;
            }

```

Create a new project, move code there and call from Controller . It should be put into a new project for testing purposes and clarity of controller ( usually, a controller should contain a single call and maybe a try/catch to return BadRequest and/or other HTTP codes)

**Comment by adrian-badulescu** [comment]
done
